services:
  db:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rust_book_ai
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
